chapters = ["Chapter 1", "Chapter 2","Chapter 3","Chapter 4","Chapter 5","Chapter 6", "Chapter 7", "Chapter 8", "Chapter 9", "Chapter 10","Chapter 11","Chapter 12","Chapter 13","Chapter 14","Chapter 15","Chapter 16","Chapter 17","Chapter 18","Chapter 19","Chapter 20","Chapter 21","Chapter 22","Chapter 23","Chapter 24","Chapter 25","Chapter 26","Chapter 27","Chapter 28","Chapter 29","Chapter 30","Chapter 31","Chapter 32","Chapter 33","Chapter 34","Chapter 35","Chapter 36","Chapter 37","Chapter 38","Chapter 39","Chapter 40","Chapter 41","Chapter 42","Chapter 43","Chapter 44","Chapter 45","Chapter 46","Chapter 47","Chapter 48","Chapter 49","Chapter 50","Chapter 51","Chapter 52","Chapter 53","Chapter 54","Chapter 55","Chapter 56","Chapter 56","Chapter 57","Chapter 58"  ]
chapter_1 = ("CompTia A+", 58 , "Chapters")
chapter_2 = ("Laptop Hardwares")
chapter_3 = ("Laptop Displays")
chapter_4 = ("Connecting Mobile Devices")
chapter_5 = ("Mobile Devices Accessories")
chapter_6 = ("Cellular Standards")
chapter_7 = ("Mobile Device Connectivity")
chapter_8 = ("Mobile Device Configurations")
chapter_9 = ("Introduction to IP")
chapter_10 = ("Common Network Ports")
chapter_11 = ("Network Devices")
chapter_12 = ("Software Defined Networks")
chapter_13 = ("Wireless Network Standards")
chapter_14 = ("Wireless Network Technologies")
chapter_15 = ("Network Services")
chapter_16 = ("IPv4 and IPv6")
chapter_17 = ("Assigning IP addresses")
chapter_18 = ("DNS Configuration")
chapter_19 = ("DHCP Configuration")
chapter_20 = ("VLANs and VPNs")
chapter_21 = ("Internet Connection Types")
chapter_22 = ("Network Types")
chapter_23 = ("Network Tools")
chapter_24 = ("Network Cables")
chapter_25 = ("Optical Fiber")
chapter_26 = ("568A and 568B Colors")
chapter_27 = ("Peripheral Cables")
chapter_28 = ("Video Cables")
chapter_29 = ("SATA Device Cable")
chapter_30 = ("SCSI Device Cable")
chapter_31 = ("PATA Device Cable")
chapter_32 = ("Adapters and Converters")
chapter_33 = ("Copper Connectors")
chapter_34 = ("Fiber Connectors")
chapter_35 = ("An Overview Of Memory")
chapter_36 = ("Memory Technology")
chapter_37 = ("Storage Devices")
chapter_38 = ("RAID")
chapter_39 = ("Motherboard Form Factor")
chapter_40 = ("Motherboard Expansion Slot")
chapter_41 = ("Motherboard Connectors")
chapter_42 = ("Motherboard Compatibility")
chapter_43 = ("The BIOS")
chapter_44 = ("BIOS Settings")
chapter_45 = ("CPU Features")
chapter_46 = ("Expansion Cards")
chapter_47 = ("Cooling")
chapter_48 = ("Computer Power")
chapter_49 = ("Multi Function Devices")
chapter_50 = ("Laser Printers")
chapter_51 = ("Laser Printer Maintainance")
chapter_52 = ("Inkjet Printers")
chapter_53 = ("Inket Printer Maintainance")
chapter_54 = ("Thermal Printers")
chapter_55 = ("Thermal Printer Maintainance")
chapter_56 = ("Impact Printers")
chapter_57 = ("Impact Printer Maintainance")
chapter_58 = ("3D Printers")



chapter_2 ={"Laptop Batteries":("Lithium-Ion Li-ion","Lithium-Ion Polymer LiPo"),"Laptop Memories":("SO-DIMM Small Outline Dual In-line Memory Module"),
"Laptop Storage":("Magnetic Disk","Solid State Drive SSD", "M.2"),"Migrating from HDD to SSD": ("An Impressive Ugrade", "Install an OS on the SSD", "Create a clone/Image of the HDD, then move to the other Drive", "Imaging Software needed", "Creating an Image file", "Drive to Drive Image"),
"Wireless network connectivity":("802.11","Bluetooth","Mini PCI","Mini PCI Express"),
"Laptop Security":("Biometric","Password","Near Field Communication -NFC")}
chapter_3 = {"Laptop Display":("Portable Liquid Crystal Display--Twisted Nematic LCD,In Plane switching LCD,Vertical Alignment LCD","OLED--Organic Light Emitting Diode "), "Wi-Fi Antennas":("Wifi main and AUX", "Bluetooth", "All antennas are wrapped up on the display area"), "Webcam":("Camera ", "Audio "), "LCD Requirement":("Cold Cathode Flourescent Lamp")}
chapter_4 = {"Mobile Device Connection USB":("Micro B Plug","Mini B Plug","Type A Plug", "USB C Plug"), "Serial Interfaces":("DB-9","RS-232",), "Near Field Communication":("Payment System","Transportation", "in person information exchange"), "Bluetooth":("Personal Area Network"), "Hotspot":"Personal Wireless Router"}
chapter_5 = {"Mobile Devices Accessories":("Touch pen","Digital Stylus", "Drawing pad", "Trackpads", )}
chapter_6 = {"Cellular Standards":("2G","GSM","CDMA","3G --GSM & CDMA","4G LTE","5G")}
chapter_7 = {"Mobile Device Connectivity":("Bluetooth","Global Positioning System", "Mobile Devices determines location based on GPS,Wifi, and cellular tower", "Mobile Device Management")}
gps = {"Global Positioning System":("Needs at least 4 satellites to get precise location", "Determines location based on timing differences--Longitude,LAtitude,Altitude")}
mdm = {"Mobile Devvice Management":("manage company-owned devices and user-owned devices from a console","Set policies on apps, data, camera etc", "manage access control", "corporate email configuration", "Two-factor authentication","corporate applications--allow/restrict app installation---prevent unauthorized app usage")}
chapter_8 = {"Mobile Device Configurations":("Text message and other seettings are pre-configured","Email services-Microsoft365","Data types that can be synchronized--Mail,pictures/music/videos,calender,contacts")}
chapter_9 = {"Introduction to IP":("TCP and UDP are the common way or mode of transportation of data in the Internet Protocol"),"UDP used cases":"These are called connectionless protocols and examples are DHCP and TFTP", "TCP used cases":"These are called connection-oriented protocols and it uses a return receipt i.e aknowledges a data has been sent, and delivered successfully..Example ---HTTPS and SSH", "port_numbers":"TCP and UDP port numbers can be any number from 0 - 65535"}
ip_hierachy = {"road":"Ethernet,DSL,cable system","road":"Internet Protocol", "boxes":"TCP and UDP data hodler","TCP & UDP data":("Application information"),"box_label":"These are box name otherwise known/ best known  as port numbers to the computer system and it shows where the box belongs to "}
ip_architecture = {"breakdown1":("Ethernet Header","Ethernet Payload","Ethernet Trailer"), "breakdown2":("Ethernet Header","IP","IP Payload","Ethernet Trailer"), "breakdown3":("Ethernet Header","IP", "TCP", "TCP Payload","Ethernet Trailer"), "breakdown4":("Ethernet Header","IP", "TCP", "HTTP data","Ethernet Trailer")}
ip_terms = {"TCP":"Transmission Control Protocol", "UDP":"User Datagram Prootocol", "DHCP":"Dynamic Host Configuration Protocol", "TFTP":"Trivial File Transfer Protocol", "HTTPS":"Hyper-Text Transfer Protocol Secure", "SSH":"Secure Shell"}
ip_flow = {"To have a successful data transfer on IP, we need" "serverSide":("Server IP Address", "protocol", "Server Application port number"), "clientSide":("Client IP Address","protocol","client port number")}
ip_ports = {"Non-ephemeral ports/permanent port numbers":"Ports 0 - 1023","Ephemeral ports/Temporary port numbers":"1024-65535...Determined in real time by client"}